version: 2.1
executors:
  maven-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project
jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-cache-{{ checksum "pom.xml" }}
            - maven-cache-
      - run:
          name: Build with Maven
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-cache-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/
          destination: build-artifacts
workflows:
  version: 2
  build-deploy:
    jobs:
      - build