version: 2.1
jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: npm-cache-{{ checksum "package-lock.json" }}
  run_playwright_tests:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run Playwright Tests
          command: npx playwright test
workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_playwright_tests:
          requires:
            - install_dependencies